FROM python

WORKDIR /api

RUN pip install "fastapi[standard]"
RUN pip install requests
RUN pip install psycopg2
RUN pip install datetime
RUN pip install sqlalchemy

COPY ./api /api

CMD ["fastapi", "run", "./main.py", "--port", "80"]